### PR TITLE
Compress field images with oxipng

### PR DESCRIPTION
**Pull request by Gold856**
I used [oxipng](https://github.com/shssoichiro/oxipng) with the arguments `-Z -o max --fast` to compress each image, then a second pass with `-o max --fast --strip safe` to squeeze a few more bytes out. This reduced the size of the field images by ~50%, and reduced the size of the whole app by ~25%.

### CODE REVIEW

**Comment by Gold872** [comment]
I think this is a good improvement to add. I'd prefer adding this as a GitHub CI action so it doesn't have to be done manually when new images are added

**Comment by Gold856** [comment]
The CI workflow has been added as a comment command `/optimize`. You'll need to add a sercet called `IMAGE_COMPRESSOR_TOKEN` that has push access to allow GitHub Actions to commit and push to PR branches.

**Comment by Gold872** [comment]
What I was originally thinking for the CI is for it to compress the images before building, that way it's done automatically without any need for comment commands or github tokens

**Comment by Gold856** [comment]
We’d need a token anyways to be able to push commits and I’m not a big fan of adding commits to a PR automatically. The compression process also takes several minutes (20+ per image), and I don’t want to hold up a build just for that. I think just running an optimize command every time a PNG is modified/added is a good compromise (I doubt PNGs are modified/added often anyways).

**Comment by Gold872** [comment]
Since it takes that long to optimize the images I think it's best to just remove the CI do the compression manually. You're right that there's only a new image once a year, and now that I think of it, trying to simplify it ends up creating more work.

I appreciate your work on this I think this is a good enhancement

**Pull request merged**
