### PR TITLE
added dark mode & theme features

### PR DESCRIPTION
**Pull request by DanPeled**

### CODE REVIEW

**Comment by Gold872** [comment]
I was able to get the light mode to look okay-ish, but there's a big issue with having to update all the widgets on the screen whenever the brightness changes, which right now the app isn't really structured to do since not all widgets can be rebuilded on command (which is why many apps require restarting after changing themes).

For now I'll push the changes for the dark mode theming and work from there, what might have to be done is add a pop-up warning the user that the app will have to be restarted for all the theme changes to take effect

**Comment by DanPeled** [comment]
> I was able to get the light mode to look okay-ish, but there's a big issue with having to update all the widgets on the screen whenever the brightness changes, which right now the app isn't really structured to do since not all widgets can be rebuilded on command (which is why many apps require restarting after changing themes).
> 
> For now I'll push the changes for the dark mode theming and work from there, what might have to be done is add a pop-up warning the user that the app will have to be restarted for all the theme changes to take effect

Ye that makes sense, I didn't really like how the light mode looks how I made it anyway (Not really a fan of light mode, hurts my eyes)

**Comment by DanPeled** [comment]
> > Ye that makes sense, I didn't really like how the light mode looks how I made it anyway (Not really a fan of light mode, hurts my eyes)
> 
> In that case I suggest removing the light mode feature and have only the theme variant selection feature available

ill make a new PR then

**Comment by Gold872** [comment]
This PR should fix #33

**Pull request merged**
