### PR TITLE
Adds Python Support for elasticlib

### PR DESCRIPTION
**Pull request by Ryanforce08**
Used Black Formatting and WPI Format

### CODE REVIEW

**Comment by DanPeled** [comment]
Already am @Ryanforce08

**Comment by DanPeled** [comment]
This is a duplicate PR (#136 already exists)

**Comment by Ryanforce08** [comment]
Dang I did not see. yours is better anyways

**Comment by DanPeled** [comment]
i would recommend closing the PR then

**Comment by Ryanforce08** [comment]
Just realized mine has better docs is there away to add my docs to yours

**Comment by DanPeled** [comment]
> Just realized mine has better docs is there away to add my docs to yours

I am copying the docs from the Java & C++ versions

**Pull request closed without merging**
